name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

# These permissions are needed for OIDC authentication
permissions:
  id-token: write # This is required for OIDC
  contents: read  # This is required to checkout the code
  pull-requests: write # This is required for commenting on PRs

env:
  AZURE_RG_NAME: aim-possible-rg
  AZURE_LOCATION: westeurope
  AZURE_APP_PLAN: aim-possible-plan
  AZURE_FRONTEND_APP: aim-possible-frontend
  AZURE_BACKEND_APP: aim-possible-backend
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: Azure login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false # We don't need PowerShell
        audience: api://AzureADTokenExchange # This is the default audience for OIDC

    - name: Validate Azure access
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Verify we have the correct permissions
          az account show
          az group show --name ${{ env.AZURE_RG_NAME }} || echo "Resource group does not exist yet"
    
    - name: Create Azure resources
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Create resource group if it doesn't exist
          az group create --name ${{ env.AZURE_RG_NAME }} --location ${{ env.AZURE_LOCATION }}
          
          # Create App Service Plan
          az appservice plan create \
            --name ${{ env.AZURE_APP_PLAN }} \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --sku B1 \
            --is-linux || echo "App Service Plan already exists"

          # Create Backend Web App (Node.js)
          az webapp create \
            --name ${{ env.AZURE_BACKEND_APP }} \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --plan ${{ env.AZURE_APP_PLAN }} \
            --runtime "NODE|18-lts" || echo "Backend app already exists"

          # Create Frontend Web App (Static files)
          az webapp create \
            --name ${{ env.AZURE_FRONTEND_APP }} \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --plan ${{ env.AZURE_APP_PLAN }} \
            --runtime "NODE|18-lts" || echo "Frontend app already exists"

    - name: Configure Backend Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Configure Backend App Settings and Environment Variables
          az webapp config appsettings set \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_BACKEND_APP }} \
            --settings \
              PORT=8080 \
              NODE_ENV=production \
              FRONTEND_URL=https://${{ env.AZURE_FRONTEND_APP }}.azurewebsites.net \
              WEBSITE_NODE_DEFAULT_VERSION=~18 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              ENABLE_ORYX_BUILD=true

          # Configure startup file for backend
          az webapp config set \
            --name ${{ env.AZURE_BACKEND_APP }} \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --startup-file "node index.js" \
            --always-on true

          # Enable logging
          az webapp log config \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_BACKEND_APP }} \
            --web-server-logging filesystem \
            --application-logging filesystem

          # Configure CORS for Backend
          az webapp cors add \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_BACKEND_APP }} \
            --allowed-origins \
              https://${{ env.AZURE_FRONTEND_APP }}.azurewebsites.net \
              http://localhost:5173 \
              http://localhost:4173

    - name: Configure Frontend Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Configure Frontend App Settings for serving static files
          az webapp config appsettings set \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_FRONTEND_APP }} \
            --settings \
              NODE_ENV=production \
              WEBSITE_NODE_DEFAULT_VERSION=~18 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=false \
              ENABLE_ORYX_BUILD=false \
              PORT=8080 \
              WEBSITE_RUN_FROM_PACKAGE=0 \
              ORYX_DEFAULT_APP_FILE_PATH=server.js \
              SCM_COMMAND_IDLE_TIMEOUT=7200

          # Configure startup file for frontend (use Node.js server)
          az webapp config set \
            --name ${{ env.AZURE_FRONTEND_APP }} \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --startup-file "node server.js" \
            --always-on true

          # Enable logging
          az webapp log config \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_FRONTEND_APP }} \
            --web-server-logging filesystem \
            --application-logging filesystem \
            --level verbose

          # Restart the app to apply new settings
          az webapp restart \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_FRONTEND_APP }}

    - name: Install and Build Frontend
      run: |
        cd frontend
        # Use npm install instead of npm ci to handle package-lock.json sync issues
        npm install
        # Build the frontend (this will run the postbuild script automatically)
        npm run build
        # Verify that the dist folder has the required files
        echo "Checking dist folder contents..."
        ls -la dist/
        echo "Checking if server.js exists in dist..."
        ls -la dist/server.js || echo "❌ server.js not found in dist"
        echo "Checking if package.json exists in dist..."
        ls -la dist/package.json || echo "❌ package.json not found in dist"
        # Install production dependencies in the dist folder for deployment
        cd dist
        # Only install if package.json exists
        if [ -f package.json ]; then
          npm install --omit=dev
          echo "✅ Dependencies installed in dist folder"
        else
          echo "❌ No package.json found in dist folder"
          exit 1
        fi
      env:
        VITE_API_URL: https://${{ env.AZURE_BACKEND_APP }}.azurewebsites.net
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        # Install dependencies, use install instead of ci for flexibility
        npm install --only=production
    
    - name: Deploy Frontend
      if: false  # Temporarily disabled - using CLI deployment instead
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FRONTEND_APP }}
        package: frontend/dist
    
    - name: Restart Frontend App
      if: false  # Temporarily disabled - using CLI deployment instead
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "🔄 Restarting frontend app to ensure new deployment is active..."
          az webapp restart \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_FRONTEND_APP }}
          echo "✅ Frontend app restarted"

    - name: Alternative Frontend Deployment (CLI)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "🚀 Starting alternative CLI deployment for frontend..."
          
          # Create a deployment package
          cd frontend/dist
          echo "📦 Creating deployment package..."
          zip -r ../frontend-deployment.zip . -x "*.git*" "*.gitignore*"
          cd ..
          
          echo "📋 Package contents verification..."
          unzip -l frontend-deployment.zip | head -20
          
          # Deploy using Azure CLI
          echo "🎯 Deploying to Azure App Service via CLI..."
          az webapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_FRONTEND_APP }} \
            --src frontend-deployment.zip \
            --timeout 600
          
          echo "✅ CLI deployment completed"
          
          # Restart the app
          echo "🔄 Restarting frontend app..."
          az webapp restart \
            --resource-group ${{ env.AZURE_RG_NAME }} \
            --name ${{ env.AZURE_FRONTEND_APP }}
          echo "✅ Frontend app restarted"

    - name: Deploy Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_BACKEND_APP }}
        package: backend

    - name: Verify Deployment
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "🚀 Starting deployment verification..."
          backend_url="https://${{ env.AZURE_BACKEND_APP }}.azurewebsites.net"
          frontend_url="https://${{ env.AZURE_FRONTEND_APP }}.azurewebsites.net"
          
          echo "Backend URL: $backend_url"
          echo "Frontend URL: $frontend_url"
          
          # Wait longer for deployment to complete
          echo "⏳ Waiting 60 seconds for deployment to complete..."
          sleep 60
          
          # Check backend health with retries
          echo "🔍 Checking backend health..."
          backend_attempts=0
          backend_max_attempts=5
          while [ $backend_attempts -lt $backend_max_attempts ]; do
            backend_attempts=$((backend_attempts + 1))
            echo "Backend attempt $backend_attempts/$backend_max_attempts..."
            
            if curl -f -s --max-time 30 "$backend_url/health"; then
              echo "✅ Backend is healthy"
              break
            else
              echo "❌ Backend health check failed (attempt $backend_attempts)"
              if [ $backend_attempts -eq $backend_max_attempts ]; then
                echo "📋 Downloading backend logs for debugging..."
                az webapp log download --resource-group ${{ env.AZURE_RG_NAME }} --name ${{ env.AZURE_BACKEND_APP }} || echo "Failed to download backend logs"
              else
                echo "⏳ Waiting 30 seconds before retry..."
                sleep 30
              fi
            fi
          done
          
          echo ""
          echo "🔍 Checking frontend health..."
          frontend_attempts=0
          frontend_max_attempts=5
          while [ $frontend_attempts -lt $frontend_max_attempts ]; do
            frontend_attempts=$((frontend_attempts + 1))
            echo "Frontend attempt $frontend_attempts/$frontend_max_attempts..."
            
            # Check frontend health endpoint first
            if curl -f -s --max-time 30 "$frontend_url/health"; then
              echo "✅ Frontend health endpoint is working"
              break
            else
              echo "⚠️ Frontend health endpoint failed, checking main page..."
              
              # Check frontend main page
              if curl -f -s --max-time 30 "$frontend_url"; then
                echo "✅ Frontend main page is accessible"
                break
              else
                echo "❌ Frontend accessibility check failed (attempt $frontend_attempts)"
                if [ $frontend_attempts -eq $frontend_max_attempts ]; then
                  echo "📋 Downloading frontend logs for debugging..."
                  az webapp log download --resource-group ${{ env.AZURE_RG_NAME }} --name ${{ env.AZURE_FRONTEND_APP }} || echo "Failed to download frontend logs"
                  
                  echo "📊 Checking app status..."
                  az webapp show --resource-group ${{ env.AZURE_RG_NAME }} --name ${{ env.AZURE_FRONTEND_APP }} --query "{state:state,hostNames:defaultHostName}" --output table
                else
                  echo "⏳ Waiting 30 seconds before retry..."
                  sleep 30
                fi
              fi
            fi
          done
          
          echo ""
          echo "🔗 Application URLs:"
          echo "Backend URL: $backend_url"
          echo "Backend Health: $backend_url/health"
          echo "Frontend URL: $frontend_url"
          echo "Frontend Health: $frontend_url/health"
          
          echo ""
          echo "📊 Final status check..."
          az webapp list --resource-group ${{ env.AZURE_RG_NAME }} --query "[].{name:name,state:state,defaultHostName:defaultHostName}" --output table
